name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Packages
        run: yarn install
      - name: Run Eslint
        run: yarn lint
